import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#7f2831',
        'tertiary-fixed-dim': '#ffb3b5',
        'on-secondary-fixed': '#121e19',
        'tertiary-fixed': '#ffdada',
        'on-secondary-container': '#aab9b0',
        'on-error-container': '#ffdad6',
        'secondary-fixed-dim': '#bbcac1',
        'on-background': '#dde4df',
        primary: '#72db9f',
        'surface-container-highest': '#2f3633',
        'surface-container-lowest': '#09100d',
        'surface-dim': '#0e1512',
        'on-primary-fixed-variant': '#005230',
        'on-secondary': '#26332d',
        'primary-container': '#37a36c',
        'inverse-surface': '#dde4df',
        outline: '#889489',
        error: '#ffb4ab',
        'on-primary': '#003920',
        'surface-tint': '#72db9f',
        tertiary: '#ffb3b5',
        'primary-fixed': '#8ef8b9',
        'on-tertiary-fixed': '#40000b',
        'on-surface': '#dde4df',
        'error-container': '#93000a',
        'inverse-primary': '#006d41',
        'inverse-on-surface': '#2b322e',
        'on-error': '#690005',
        'outline-variant': '#3e4941',
        'surface-container-low': '#161d1a',
        'on-primary-fixed': '#002110',
        'surface-container': '#1a211e',
        'surface-bright': '#333b37',
        'on-tertiary': '#61101c',
        'on-tertiary-container': '#570816',
        'on-primary-container': '#00311b',
        'surface-container-high': '#242c28',
        'tertiary-container': '#dd7076',
        secondary: '#bbcac1',
        'on-secondary-fixed-variant': '#3c4a43',
        background: '#0e1512',
        'secondary-fixed': '#d7e6dd',
        surface: '#0e1512',
        'secondary-container': '#3c4a43',
        'surface-variant': '#2f3633',
        'on-surface-variant': '#bdcabe',
        'primary-fixed-dim': '#72db9f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '16px',
        'container-max': '1280px',
        xs: '4px',
        base: '8px',
        sm: '8px',
        lg: '24px',
        xl: '48px',
        gutter: '24px',
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        'max-width': '1280px',
      },
      fontFamily: {
        h2: ['Manrope'],
        'body-sm': ['Manrope'],
        'body-lg': ['Manrope'],
        display: ['Manrope'],
        'body-md': ['Manrope'],
        h1: ['Manrope'],
        label: ['Manrope'],
        h3: ['Manrope'],
        'h1-mobile': ['Manrope'],
      },
      fontSize: {
        h2: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        display: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        h1: ['32px', { lineHeight: '1.25', fontWeight: '700' }],
        label: ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'h1-mobile': ['28px', { lineHeight: '1.3', fontWeight: '700' }],
      },
    },
  },
  plugins: [forms, containerQueries],
}
